name: liquid_morph_ui
description: "A high-performance Flutter UI kit for Glassmorphism and behavior-driven Liquid Glass bottom navigation bars."
version: 1.0.3
homepage: https://github.com/vaibhav201102/liquid_morph_ui
repository: https://github.com/vaibhav201102/liquid_morph_ui
issue_tracker: https://github.com/vaibhav201102/liquid_morph_ui/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
